[package]
name = "papertrail-downloader"
version = "0.1.0"
authors = ["ndelvalle <nicolas.delvalle@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.15"
clap = "2.33.3"
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["macros", "fs"] }
reqwest = { version = "0.10.7", features = ["stream"] }
shellexpand = "2.0.0"
indicatif = "0.15.0"
